name: Static analysis
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Go modules
        run: |
          make update-gomod
          git diff --exit-code

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-lxc/daily -y
          sudo apt-get install -qq lxc-dev pkg-config libdbus-1-dev libseccomp-dev libcap-dev
          go install golang.org/x/lint/golint@latest
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Static analysis
        run: make all
