name: Static analysis
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Go modules
        run: |
          make update-gomod
          git diff --exit-code

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-lxc/daily -y
          sudo apt-get install -qq lxc-dev pkg-config
          go get golang.org/x/lint/golint
          go get golang.org/x/tools/cmd/goimports

      - name: Static analysis
        run: make all
